version: "3"

services:
  web:
    image: jamiecaldwell/uh-crw:latest
    command: R -e "uhnoaashinyapp::run_app(port=structure('/app/socks/shiny.sock', mask=384), host='66.228.47.179')"
    volumes:
      - /srv/socks:/app/socks
