version: "3"

services:
  web:
    image: jamiecaldwell/uh-crw:latest
    command: R -e "require(uhnoaashinyapp); app_global(); shiny::runApp('/app/codes/forec_shiny_app.R', port=structure('/app/socks/shiny.sock', mask=384))"
    volumes:
      - /srv/socks:/app/socks
