version: "3"

services:
  web:
    image: jamiecaldwell/uh-crw:latest
    command: R -e "uhnoaashinyapp::run_app(main_dir = '.', port=structure('/app/socks/shiny.sock', mask=384))"
    volumes:
      - /srv/socks:/app/socks
