if (!require("flexdashboard")) install.packages("flexdashboard"); library(flexdashboard)
if (!require("leaflet")) install.packages("leaflet"); library(leaflet)
if (!require("plotly")) install.packages("plotly"); library(plotly)
if (!require("shiny")) install.packages("shiny"); library(shiny)
if (!require("shinyBS")) install.packages("shinyBS"); library(shinyBS) # for hover text
if (!require("shinycssloaders")) install.packages("shinycssloaders"); library(shinycssloaders)
if (!require("shinydashboard")) install.packages("shinydashboard"); library(plotly)
if (!require("shinythemes")) install.packages("shinythemes"); library(shinythemes)
if (!require("shinyWidgets")) install.packages("shinyWidgets"); library(shinyWidgets)
if (!require("tidyverse")) install.packages("tidyverse"); library(tidyverse)
if (!require("xts")) install.packages("xts"); library(xts)
