name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HOST: "66.228.47.179"
      DOCKER_STACK_NAME: coral
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_ID: jamiecaldwell

    steps:
      # Check out GitHub reportiory
      - uses: actions/checkout@v2

      - name: Checkout transcrypt
        uses: actions/checkout@v2
        with:
          repository: elasticdog/transcrypt
          path: transcrypt

      - name: Initialise transcrypt
        run: ./transcrypt/transcrypt -c aes-256-cbc -p '${{ secrets.TRANSCRYPT_PASSWORD }}' --yes

      # Build the Docker image
      - name: Build container image
        run: |
          DOCKER_BUILDKIT=1 docker build \
          --tag jamiecaldwell/uh-crw:latest \
          --cache-from jamiecaldwell/uh-crw:latest \
          --build-arg BUILDKIT_INLINE_CACHE=1 .

      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: jamiecaldwell
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push the image to DockerHub
      - name: Push container image
        run: docker push jamiecaldwell/uh-crw:latest

      # Deploy the image to the webserver.
      - name: Run deploy script
        run: ./infra/deploy.sh
        shell: bash