name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      R_KEEP_PKG_SOURCE: yes
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      - name: Define Docker metadata
        id: docker_metadata
        uses: docker/metadata-action@v4
        with:
          images: jamiecaldwell/uh-crw
          tags: |
            type=raw,value=latest
            type=semver,pattern={{raw}} 


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: jamiecaldwell
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout transcrypt
        uses: actions/checkout@v3
        with:
          repository: elasticdog/transcrypt
          path: transcrypt

      - name: Initialise transcrypt
        run: ./transcrypt/transcrypt -p '${{ secrets.TRANSCRYPT_PASSWORD }}' --yes


      - name: Build container image and push to dockerhub on a tagged release
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ steps.docker_metadata.outputs.tags }}
          cache-from: type=registry,ref=jamiecaldwell/uh-crw:latest
          cache-to: type=inline
          push: true # ${{ github.event_name == 'release' }}
          build-args: |
            "event_sha=${{ github.sha }}"

      - name: Deploy the image to the webserver on a tagged release
        if: true # ${{ github.event_name == 'release' }}
        run: ./infra/deploy.sh
        shell: bash
        env: 
          HOST: "66.228.47.179"
          DOCKER_STACK_NAME: coral
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_ID: jamiecaldwell