name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HOST: "66.228.47.179"
      DOCKER_STACK_NAME: coral
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_ID: jamiecaldwell
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Checkout transcrypt
        uses: actions/checkout@v3
        with:
          repository: elasticdog/transcrypt
          path: transcrypt

      - name: Initialise transcrypt
        run: ./transcrypt/transcrypt -c aes-256-cbc -p '${{ secrets.TRANSCRYPT_PASSWORD }}' --yes

      - name: Build container image
        run: |
          DOCKER_BUILDKIT=1 docker build \
          --tag jamiecaldwell/uh-crw:latest \
          --cache-from jamiecaldwell/uh-crw:latest \
          --build-arg BUILDKIT_INLINE_CACHE=1 .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: jamiecaldwell
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Define Docker metadata
        id: docker_metadata
        uses: docker/metadata-action@v4
        with:
          tags: |
            type=raw,value=latest
            type=semver,pattern={{raw}} 

      - name: echo_test
        run: echo "hi hello  ${{ steps.docker_metadata.outputs.tags }}"

      - name: Push image to DockerHub
        if: ${{ github.event_name == 'release' }}
        run: docker push jamiecaldwell/uh-crw:latest

      - name: Deploy the image to the webserver
        if: ${{ github.event_name == 'release' }}
        run: ./infra/deploy.sh
        shell: bash
