# This is a manual action that requires a 'button push' workflow dispatch.
# The action *does not* build the docker image, it simply deploys the existing image to the shiny server.
# The build.yml action does both the building and deploying.

name: Deploy

on:
  - workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HOST: "66.228.47.179"
      DOCKER_STACK_NAME: coral
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_ID: jamiecaldwell

    steps:
      - uses: actions/checkout@v3

      - name: Checkout transcrypt
        uses: actions/checkout@v3
        with:
          repository: elasticdog/transcrypt
          path: transcrypt

      - name: Initialise transcrypt
        run: ./transcrypt/transcrypt -c aes-256-cbc -p '${{ secrets.TRANSCRYPT_PASSWORD }}' --yes

      - name: Run deploy script
        run: ./infra/deploy.sh
        shell: bash
